version: '3.8'
services:
    frontend:
        container_name: "frontend"
        build: ./frontend/
        ports:
            - 8888:3000
        volumes:
            - ./frontend/app:/usr/src/app
        command: yarn start

    backend:
        container_name: "backend"
        build: ./backend/
        ports:
            - 8080:3000
        volumes:
            - ./backend/app:/usr/src/app
        depends_on:
            - database
        command: yarn start

    database:
        restart: always
        image: mongo:latest
        container_name: "database"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/:/data/db
        ports:
            - 27017:27017
        command: mongod --logpath=/dev/null --smallfiles